 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.h
 *
 * Description: header file for the ultrasonic driver
 *
 * Author: Ali Elnashar
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ULTRASONIC_ECHO_PORT   PORTD_ID
#define ULTRASONIC_ECHO_PIN    PIN6_ID
#define ULTRASONIC_TRIGGER_PORT  PORTB_ID
#define ULTRASONIC_TRIGGER_PIN   PIN5_ID
#define LIGHT_SPEED_IN_CM   34700
#define CONVERTING_SECOND_TO_MICRO  1000000
/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * initialize the ICU driver as required
 * Setup the ICU call back function
 * Setup the direction for the trigger pin as output pin through the GPIO driver..
 */
void Ultrasonic_init(void);
/*
 * Description :
 *Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void);
/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 *Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);
/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
